In [80]:
import os
import skimage
import sys
import glob
import matplotlib.pyplot as plt
# root_folder = os.path.dirname(os.getcwd())
# sys.path.append(root_folder)
from astropy.io import fits

%pylab

Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib


In [28]:
filename = 'Image000_00489.fits'

In [32]:
_hdulist = fits.open('Image000_00490.fits')

In [30]:
hdulist.info()

Filename: Image000_00489.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU      12   (512, 512)   int16   


In [23]:
hdulist[0].data

array([[ 2,  7, 16, ..., 21, 34, 33],
       [10, 10, 14, ..., 14, 31, 26],
       [ 6, 12,  4, ..., 18, 23, 19],
       ..., 
       [26, 25, 28, ..., 23, 29, 24],
       [22, 42, 26, ..., 29, 31, 26],
       [30, 58, 26, ..., 34, 30, 35]], dtype=int16)

In [34]:
hdulist.append(_hdulist[0])

In [35]:
hdulist.info()

Filename: Image000_00489.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU      12   (512, 512)   int16   
  1                1 ImageHDU        13   (512, 512)   int16   


In [36]:
hdulist[0].data

array([[ 2,  7, 16, ..., 21, 34, 33],
       [10, 10, 14, ..., 14, 31, 26],
       [ 6, 12,  4, ..., 18, 23, 19],
       ..., 
       [26, 25, 28, ..., 23, 29, 24],
       [22, 42, 26, ..., 29, 31, 26],
       [30, 58, 26, ..., 34, 30, 35]], dtype=int16)

In [37]:
hdulist[1].data

array([[11, 12, 17, ..., 20, 28, 31],
       [10,  9,  9, ..., 14, 24, 30],
       [11, 10,  6, ..., 23, 15, 21],
       ..., 
       [26, 25, 14, ..., 26, 24, 18],
       [21, 39, 31, ..., 30, 33, 32],
       [44, 49, 29, ..., 51, 37, 32]], dtype=int16)

In [39]:
hdulist[0].data + hdulist[1].data

array([[ 13,  19,  33, ...,  41,  62,  64],
       [ 20,  19,  23, ...,  28,  55,  56],
       [ 17,  22,  10, ...,  41,  38,  40],
       ..., 
       [ 52,  50,  42, ...,  49,  53,  42],
       [ 43,  81,  57, ...,  59,  64,  58],
       [ 74, 107,  55, ...,  85,  67,  67]], dtype=int16)

In [93]:
_list_files = glob.glob('/Users/y9z/Documents/Neutron_data/IPTS_19558/resonance_data/CT_runs/CT_peaks/U/peaks/*.fits')
_list_files

['/Users/y9z/Documents/Neutron_data/IPTS_19558/resonance_data/CT_runs/CT_peaks/U/peaks/Image000_00514.fits',
 '/Users/y9z/Documents/Neutron_data/IPTS_19558/resonance_data/CT_runs/CT_peaks/U/peaks/Image000_00515.fits',
 '/Users/y9z/Documents/Neutron_data/IPTS_19558/resonance_data/CT_runs/CT_peaks/U/peaks/Image000_00516.fits',
 '/Users/y9z/Documents/Neutron_data/IPTS_19558/resonance_data/CT_runs/CT_peaks/U/peaks/Image000_00517.fits',
 '/Users/y9z/Documents/Neutron_data/IPTS_19558/resonance_data/CT_runs/CT_peaks/U/peaks/Image000_00518.fits',
 '/Users/y9z/Documents/Neutron_data/IPTS_19558/resonance_data/CT_runs/CT_peaks/U/peaks/Image000_00661.fits',
 '/Users/y9z/Documents/Neutron_data/IPTS_19558/resonance_data/CT_runs/CT_peaks/U/peaks/Image000_00662.fits',
 '/Users/y9z/Documents/Neutron_data/IPTS_19558/resonance_data/CT_runs/CT_peaks/U/peaks/Image000_00663.fits',
 '/Users/y9z/Documents/Neutron_data/IPTS_19558/resonance_data/CT_runs/CT_peaks/U/peaks/Image000_00664.fits',
 '/Users/y9z/Docume

In [101]:
commonpath=os.path.commonpath(_list_files)
commonpath

'/Users/y9z/Documents/Neutron_data/IPTS_19558/resonance_data/CT_runs/CT_peaks/U/peaks'

In [102]:
save_path = commonpath + '/sum'

In [100]:
_list_short_files = [os.path.basename(_file) for _file in _list_files]
_list_short_files


['Image000_00514.fits',
 'Image000_00515.fits',
 'Image000_00516.fits',
 'Image000_00517.fits',
 'Image000_00518.fits',
 'Image000_00661.fits',
 'Image000_00662.fits',
 'Image000_00663.fits',
 'Image000_00664.fits',
 'Image000_00665.fits',
 'Image000_00666.fits',
 'Image000_00708.fits',
 'Image000_00709.fits',
 'Image000_00710.fits',
 'Image000_00711.fits',
 'Image000_00712.fits',
 'Image000_00713.fits',
 'Image000_00888.fits',
 'Image000_00889.fits',
 'Image000_00890.fits',
 'Image000_00891.fits',
 'Image000_00892.fits',
 'Image000_00893.fits',
 'Image000_01199.fits',
 'Image000_01200.fits',
 'Image000_01201.fits',
 'Image000_01202.fits',
 'Image000_01203.fits',
 'Image000_01204.fits',
 'Image000_01205.fits',
 'Image000_01206.fits',
 'Image000_01207.fits',
 'Image000_01596.fits',
 'Image000_01597.fits',
 'Image000_01598.fits',
 'Image000_01599.fits',
 'Image000_01600.fits',
 'Image000_01601.fits',
 'Image000_01602.fits',
 'Image000_01603.fits',
 'Image000_01604.fits',
 'Image000_01605

In [87]:
os.listdir('/Users/y9z/Documents/Neutron_data/IPTS_19558/resonance_data/CT_runs/CT_peaks/U/')

['.DS_Store', 'OB', 'peaks']

In [103]:
_list_element = set([_name.split('_')[0] for _name in _list_short_files])
_list_element

{'Image000',
 'Image001',
 'Image002',
 'Image003',
 'Image004',
 'Image005',
 'Image006',
 'Image007',
 'Image008',
 'Image009',
 'Image010',
 'Image011',
 'Image012',
 'Image013',
 'Image014',
 'Image015',
 'Image016',
 'Image017',
 'Image018',
 'Image019',
 'Image020',
 'Image021',
 'Image022',
 'Image023',
 'Image024',
 'Image025',
 'Image026',
 'Image027',
 'Image028',
 'Image029',
 'Image030',
 'Image031',
 'Image032',
 'Image033',
 'Image034',
 'Image035'}

In [104]:
_list_num = set([_name.split('_')[1] for _name in _list_short_files])
_list_num

{'00514.fits',
 '00515.fits',
 '00516.fits',
 '00517.fits',
 '00518.fits',
 '00661.fits',
 '00662.fits',
 '00663.fits',
 '00664.fits',
 '00665.fits',
 '00666.fits',
 '00708.fits',
 '00709.fits',
 '00710.fits',
 '00711.fits',
 '00712.fits',
 '00713.fits',
 '00888.fits',
 '00889.fits',
 '00890.fits',
 '00891.fits',
 '00892.fits',
 '00893.fits',
 '01199.fits',
 '01200.fits',
 '01201.fits',
 '01202.fits',
 '01203.fits',
 '01204.fits',
 '01205.fits',
 '01206.fits',
 '01207.fits',
 '01596.fits',
 '01597.fits',
 '01598.fits',
 '01599.fits',
 '01600.fits',
 '01601.fits',
 '01602.fits',
 '01603.fits',
 '01604.fits',
 '01605.fits',
 '01606.fits',
 '01607.fits',
 '01608.fits',
 '01609.fits'}

In [45]:
len(_list_num)

32

In [111]:
i = 1
path = commonpath + '/'
for image_num in _list_element:
    _hdulist = fits.open(path + image_num + '_00514.fits')
    summed = 0
    for _num in _list_num:
        fname = path + image_num + '_' + _num
        _loaded_file = fits.open(fname)
        summed += _loaded_file[0].data
    _hdulist[0].data = summed
#     _hdulist.writeto(save_path + '/' + image_num + '_sum.fits')
    print(image_num)
    print(summed)


Image029
[[ 314  393  695 ...,  627  748  766]
 [ 309  308  386 ...,  465  644  744]
 [ 233  349  350 ...,  531  580  666]
 ..., 
 [ 742  800  545 ...,  670  683  633]
 [ 626  891  627 ...,  688  828  663]
 [1187 1531  726 ...,  926  821  768]]
Image028
[[ 327  398  666 ...,  620  759  757]
 [ 317  294  386 ...,  440  620  772]
 [ 251  358  342 ...,  455  536  684]
 ..., 
 [ 802  787  544 ...,  628  708  620]
 [ 608  868  641 ...,  668  825  604]
 [1237 1597  756 ...,  883  770  693]]
Image011
[[ 312  388  632 ...,  583  771  737]
 [ 318  299  386 ...,  417  637  707]
 [ 269  376  368 ...,  522  561  602]
 ..., 
 [ 809  798  501 ...,  672  764  591]
 [ 636  892  634 ...,  692  862  652]
 [1294 1632  734 ...,  916  837  718]]
Image004
[[ 325  421  660 ...,  767  987  933]
 [ 303  296  379 ...,  569  824  884]
 [ 252  382  381 ...,  605  706  771]
 ..., 
 [ 876  925  619 ...,  836  933  795]
 [ 685 1023  769 ...,  824 1052  815]
 [1391 1700  881 ..., 1209 1055  950]]
Image007
[[ 318  425

Image009
[[ 282  351  538 ...,  602  736  761]
 [ 262  230  355 ...,  449  641  757]
 [ 198  294  319 ...,  534  563  698]
 ..., 
 [ 753  805  500 ...,  345  804  679]
 [ 600  906  645 ...,  716  942  649]
 [1262 1509  748 ..., 1028  922  774]]


In [60]:
_hdulist = fits.open('Image000_00490.fits')

In [63]:
_hdulist[0].data

array([[11, 12, 17, ..., 20, 28, 31],
       [10,  9,  9, ..., 14, 24, 30],
       [11, 10,  6, ..., 23, 15, 21],
       ..., 
       [26, 25, 14, ..., 26, 24, 18],
       [21, 39, 31, ..., 30, 33, 32],
       [44, 49, 29, ..., 51, 37, 32]], dtype=int16)

In [64]:
_hdulist[0].data = summed

In [65]:
_hdulist[0].data

array([[203, 264, 445, ..., 441, 561, 567],
       [216, 186, 266, ..., 374, 482, 547],
       [156, 236, 230, ..., 411, 429, 442],
       ..., 
       [477, 534, 337, ..., 223, 532, 500],
       [418, 589, 397, ..., 516, 601, 436],
       [840, 965, 485, ..., 691, 590, 532]], dtype=int16)

In [66]:
_hdulist.writeto('test_009.fits')

In [50]:

# for image_num in _list_element:
#     summed = None
#     for _num in _list_num:
#         fname = image_num + '_' + _num
#         if summed is None:
#             summed = fits.open(fname)
#         else:
#             _loaded_file = fits.open(fname)
#             summed.append(_loaded_file[0])
#     summed.info()
# #         summed += loaded_file[0].data
# #     summed.writeto('/summed/'+image_num+'.fits')
        
        

Filename: Image029_01782.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU      12   (512, 512)   int16   
  1                1 ImageHDU        13   (512, 512)   int16   
  2                1 ImageHDU        13   (512, 512)   int16   
  3                1 ImageHDU        13   (512, 512)   int16   
  4                1 ImageHDU        13   (512, 512)   int16   
  5                1 ImageHDU        13   (512, 512)   int16   
  6                1 ImageHDU        13   (512, 512)   int16   
  7                1 ImageHDU        13   (512, 512)   int16   
  8                1 ImageHDU        13   (512, 512)   int16   
  9                1 ImageHDU        13   (512, 512)   int16   
 10                1 ImageHDU        13   (512, 512)   int16   
 11                1 ImageHDU        13   (512, 512)   int16   
 12                1 ImageHDU        13   (512, 512)   int16   
 13                1 ImageHDU        13   (512, 512)   int16   
 14         

Filename: Image007_01782.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU      12   (512, 512)   int16   
  1                1 ImageHDU        13   (512, 512)   int16   
  2                1 ImageHDU        13   (512, 512)   int16   
  3                1 ImageHDU        13   (512, 512)   int16   
  4                1 ImageHDU        13   (512, 512)   int16   
  5                1 ImageHDU        13   (512, 512)   int16   
  6                1 ImageHDU        13   (512, 512)   int16   
  7                1 ImageHDU        13   (512, 512)   int16   
  8                1 ImageHDU        13   (512, 512)   int16   
  9                1 ImageHDU        13   (512, 512)   int16   
 10                1 ImageHDU        13   (512, 512)   int16   
 11                1 ImageHDU        13   (512, 512)   int16   
 12                1 ImageHDU        13   (512, 512)   int16   
 13                1 ImageHDU        13   (512, 512)   int16   
 14         

Filename: Image015_01782.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU      12   (512, 512)   int16   
  1                1 ImageHDU        13   (512, 512)   int16   
  2                1 ImageHDU        13   (512, 512)   int16   
  3                1 ImageHDU        13   (512, 512)   int16   
  4                1 ImageHDU        13   (512, 512)   int16   
  5                1 ImageHDU        13   (512, 512)   int16   
  6                1 ImageHDU        13   (512, 512)   int16   
  7                1 ImageHDU        13   (512, 512)   int16   
  8                1 ImageHDU        13   (512, 512)   int16   
  9                1 ImageHDU        13   (512, 512)   int16   
 10                1 ImageHDU        13   (512, 512)   int16   
 11                1 ImageHDU        13   (512, 512)   int16   
 12                1 ImageHDU        13   (512, 512)   int16   
 13                1 ImageHDU        13   (512, 512)   int16   
 14         

Filename: Image002_01782.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU      12   (512, 512)   int16   
  1                1 ImageHDU        13   (512, 512)   int16   
  2                1 ImageHDU        13   (512, 512)   int16   
  3                1 ImageHDU        13   (512, 512)   int16   
  4                1 ImageHDU        13   (512, 512)   int16   
  5                1 ImageHDU        13   (512, 512)   int16   
  6                1 ImageHDU        13   (512, 512)   int16   
  7                1 ImageHDU        13   (512, 512)   int16   
  8                1 ImageHDU        13   (512, 512)   int16   
  9                1 ImageHDU        13   (512, 512)   int16   
 10                1 ImageHDU        13   (512, 512)   int16   
 11                1 ImageHDU        13   (512, 512)   int16   
 12                1 ImageHDU        13   (512, 512)   int16   
 13                1 ImageHDU        13   (512, 512)   int16   
 14         

Filename: Image023_01782.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU      12   (512, 512)   int16   
  1                1 ImageHDU        13   (512, 512)   int16   
  2                1 ImageHDU        13   (512, 512)   int16   
  3                1 ImageHDU        13   (512, 512)   int16   
  4                1 ImageHDU        13   (512, 512)   int16   
  5                1 ImageHDU        13   (512, 512)   int16   
  6                1 ImageHDU        13   (512, 512)   int16   
  7                1 ImageHDU        13   (512, 512)   int16   
  8                1 ImageHDU        13   (512, 512)   int16   
  9                1 ImageHDU        13   (512, 512)   int16   
 10                1 ImageHDU        13   (512, 512)   int16   
 11                1 ImageHDU        13   (512, 512)   int16   
 12                1 ImageHDU        13   (512, 512)   int16   
 13                1 ImageHDU        13   (512, 512)   int16   
 14         

Filename: Image030_01782.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU      12   (512, 512)   int16   
  1                1 ImageHDU        13   (512, 512)   int16   
  2                1 ImageHDU        13   (512, 512)   int16   
  3                1 ImageHDU        13   (512, 512)   int16   
  4                1 ImageHDU        13   (512, 512)   int16   
  5                1 ImageHDU        13   (512, 512)   int16   
  6                1 ImageHDU        13   (512, 512)   int16   
  7                1 ImageHDU        13   (512, 512)   int16   
  8                1 ImageHDU        13   (512, 512)   int16   
  9                1 ImageHDU        13   (512, 512)   int16   
 10                1 ImageHDU        13   (512, 512)   int16   
 11                1 ImageHDU        13   (512, 512)   int16   
 12                1 ImageHDU        13   (512, 512)   int16   
 13                1 ImageHDU        13   (512, 512)   int16   
 14         

Filename: Image035_01782.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU      12   (512, 512)   int16   
  1                1 ImageHDU        13   (512, 512)   int16   
  2                1 ImageHDU        13   (512, 512)   int16   
  3                1 ImageHDU        13   (512, 512)   int16   
  4                1 ImageHDU        13   (512, 512)   int16   
  5                1 ImageHDU        13   (512, 512)   int16   
  6                1 ImageHDU        13   (512, 512)   int16   
  7                1 ImageHDU        13   (512, 512)   int16   
  8                1 ImageHDU        13   (512, 512)   int16   
  9                1 ImageHDU        13   (512, 512)   int16   
 10                1 ImageHDU        13   (512, 512)   int16   
 11                1 ImageHDU        13   (512, 512)   int16   
 12                1 ImageHDU        13   (512, 512)   int16   
 13                1 ImageHDU        13   (512, 512)   int16   
 14         

Filename: Image008_01782.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU      12   (512, 512)   int16   
  1                1 ImageHDU        13   (512, 512)   int16   
  2                1 ImageHDU        13   (512, 512)   int16   
  3                1 ImageHDU        13   (512, 512)   int16   
  4                1 ImageHDU        13   (512, 512)   int16   
  5                1 ImageHDU        13   (512, 512)   int16   
  6                1 ImageHDU        13   (512, 512)   int16   
  7                1 ImageHDU        13   (512, 512)   int16   
  8                1 ImageHDU        13   (512, 512)   int16   
  9                1 ImageHDU        13   (512, 512)   int16   
 10                1 ImageHDU        13   (512, 512)   int16   
 11                1 ImageHDU        13   (512, 512)   int16   
 12                1 ImageHDU        13   (512, 512)   int16   
 13                1 ImageHDU        13   (512, 512)   int16   
 14         

Filename: Image001_01782.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU      12   (512, 512)   int16   
  1                1 ImageHDU        13   (512, 512)   int16   
  2                1 ImageHDU        13   (512, 512)   int16   
  3                1 ImageHDU        13   (512, 512)   int16   
  4                1 ImageHDU        13   (512, 512)   int16   
  5                1 ImageHDU        13   (512, 512)   int16   
  6                1 ImageHDU        13   (512, 512)   int16   
  7                1 ImageHDU        13   (512, 512)   int16   
  8                1 ImageHDU        13   (512, 512)   int16   
  9                1 ImageHDU        13   (512, 512)   int16   
 10                1 ImageHDU        13   (512, 512)   int16   
 11                1 ImageHDU        13   (512, 512)   int16   
 12                1 ImageHDU        13   (512, 512)   int16   
 13                1 ImageHDU        13   (512, 512)   int16   
 14         

In [51]:
summed[0].header

SIMPLE  =                    T / file does conform to FITS standard             
BITPIX  =                   16 / number of bits per data pixel                  
NAXIS   =                    2 / number of data axes                            
NAXIS1  =                  512 / length of data axis 1                          
NAXIS2  =                  512 / length of data axis 2                          
EXTEND  =                    T / FITS dataset may contain extensions            
COMMENT   FITS (Flexible Image Transport System) format is defined in 'Astronomy
COMMENT   and Astrophysics', volume 376, page 359; bibcode: 2001A&A...376..359H 
TOF     = 0.000286080000000005 / Ttime of flight from the external trigger      
TIMEBIN =             1.6E-007 / Time width of this image                       
N_COUNTS=              2391714 / Total counts in this image                     
N_TRIGS =               432000 / Number of triggers acquired                    

In [52]:
summed[1].header

XTENSION= 'IMAGE   '           / Image extension                                
BITPIX  =                   16 / array data type                                
NAXIS   =                    2 / number of array dimensions                     
NAXIS1  =                  512                                                  
NAXIS2  =                  512                                                  
PCOUNT  =                    0 / number of parameters                           
GCOUNT  =                    1 / number of groups                               
COMMENT   FITS (Flexible Image Transport System) format is defined in 'Astronomy
COMMENT   and Astrophysics', volume 376, page 359; bibcode: 2001A&A...376..359H 
TOF     = 0.000287520000000005 / Ttime of flight from the external trigger      
TIMEBIN =             1.6E-007 / Time width of this image                       
N_COUNTS=              2413405 / Total counts in this image                     
N_TRIGS =               4320

In [53]:
summed[3].header

XTENSION= 'IMAGE   '           / Image extension                                
BITPIX  =                   16 / array data type                                
NAXIS   =                    2 / number of array dimensions                     
NAXIS1  =                  512                                                  
NAXIS2  =                  512                                                  
PCOUNT  =                    0 / number of parameters                           
GCOUNT  =                    1 / number of groups                               
COMMENT   FITS (Flexible Image Transport System) format is defined in 'Astronomy
COMMENT   and Astrophysics', volume 376, page 359; bibcode: 2001A&A...376..359H 
TOF     = 0.000287040000000005 / Ttime of flight from the external trigger      
TIMEBIN =             1.6E-007 / Time width of this image                       
N_COUNTS=              2416854 / Total counts in this image                     
N_TRIGS =               4320

In [54]:
summed[4].header

XTENSION= 'IMAGE   '           / Image extension                                
BITPIX  =                   16 / array data type                                
NAXIS   =                    2 / number of array dimensions                     
NAXIS1  =                  512                                                  
NAXIS2  =                  512                                                  
PCOUNT  =                    0 / number of parameters                           
GCOUNT  =                    1 / number of groups                               
COMMENT   FITS (Flexible Image Transport System) format is defined in 'Astronomy
COMMENT   and Astrophysics', volume 376, page 359; bibcode: 2001A&A...376..359H 
TOF     = 0.000287680000000005 / Ttime of flight from the external trigger      
TIMEBIN =             1.6E-007 / Time width of this image                       
N_COUNTS=              2404940 / Total counts in this image                     
N_TRIGS =               4320

In [55]:
summed[30].header

XTENSION= 'IMAGE   '           / Image extension                                
BITPIX  =                   16 / array data type                                
NAXIS   =                    2 / number of array dimensions                     
NAXIS1  =                  512                                                  
NAXIS2  =                  512                                                  
PCOUNT  =                    0 / number of parameters                           
GCOUNT  =                    1 / number of groups                               
COMMENT   FITS (Flexible Image Transport System) format is defined in 'Astronomy
COMMENT   and Astrophysics', volume 376, page 359; bibcode: 2001A&A...376..359H 
TOF     = 0.000248639999999999 / Ttime of flight from the external trigger      
TIMEBIN =             1.6E-007 / Time width of this image                       
N_COUNTS=              2360446 / Total counts in this image                     
N_TRIGS =               4320